### ISSUE TITLE
lint param datatypes

### ISSUE THREAD

**Issue by kellrott** [galaxyproject/planemo#85] opened 2015-02-23 22:42 UTC
If a tool's input parameter's type is wrong (or misspelled) the current lint doesn't detect the error.

**Comment by jmchilton** [comment] 2015-03-04 15:27
Good idea, but duplicate of #13. Its a bit difficult because it requires a Galaxy instance and set of configuration files to reference.

**Closed by jmchilton** 2015-03-04 15:27 UTC
