### ISSUE TITLE
SAWarning when running planemo with --docker

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/planemo#1210] opened 2021-12-15 13:24 UTC
I get this when running `planemo t --docker`; I'm running planemo v. 0.74.9

`/tmp/tmpmew_j1on/galaxy-dev/lib/galaxy/jobs/handler.py:359: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  ~model.Job.table.c.id.in_(hda_not_ready),
/tmp/tmpmew_j1on/galaxy-dev/lib/galaxy/jobs/handler.py:360: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  ~model.Job.table.c.id.in_(ldda_not_ready))
`

Also, it takes quite a long time to run `planemo t --docker`. Not sure if it is related, but I guess so.

**Comment by mvdbeek** [comment] 2021-12-15 13:28
That's a duplicate of https://github.com/galaxyproject/galaxy/issues/12981 and is not a problem.

**Comment by mvdbeek** [comment] 2021-12-15 13:28
> `planemo t --docker`. Not sure if it is related, but I guess so.

If there's no mulled image the image is going to be built from the conda requirements, that can take some time

**Closed by mvdbeek** 2021-12-15 13:28 UTC

**Comment by gallardoalba** [comment] 2021-12-15 13:31
> > `planemo t --docker`. Not sure if it is related, but I guess so.
> 
> If there's no mulled image the image is going to be built from the conda requirements, that can take some time

But when running it with various xml files, it seems that it build the image for each one; Is that expected?

**Comment by mvdbeek** [comment] 2021-12-15 13:57
If they have different requirements, yes, otherwise no, it should be built once. You can see the built images in `docker images`
