### ISSUE TITLE
Planemo test 0.15.0 and 0.16.0: Targetting older Galaxy which did not produce a structured test results files.

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/planemo#331] opened 2015-10-19 10:23 UTC
Hi all,

When I run a ```planemo test``` with the most recent versions of planemo (0.15.0, 0.16.0) planemo ends with:
```
Warning: Targetting older Galaxy which did not produce a structured test results files.
There were problems with 1 test(s) - out of 1 test(s) executed. See tool_test_output.html for detailed breakdown.
```
The tool_test_output.html is a 0 byte file but the json file looks okay. This happens regardless whether the tests fail or succeed. I have tested it with defining a custom galaxy root directory (pulled today) as well as letting planemo pick it's own version of galaxy and the error doesn't go away.

I am not sure whether it is a bug or whether it is a misconfiguration from my side, but I can't figure out how to solve this.

```brew switch planemo '0.14.0'``` seems to solve it (as long as you don't uninstall) using the same galaxy root dir as for the newer versions.

Thanks for looking into this!

**Comment by remimarenco** [comment] 2015-10-19 11:43
+1 on this. We have the same trouble on Mac.

**Comment by jmchilton** [comment] 2015-10-19 12:47
I think this has been fixed by, I'll do another release:  https://github.com/galaxyproject/planemo/commit/572e7545e17ccdb37087e208febafd86a913a282

**Comment by jmchilton** [comment] 2015-10-19 13:16
0.17.0 is released - will you guys test it and let me know if the issue is resolved?

This is a fairly severe issue and ``test`` has been broken in release in the past, so I put together another issue for how I think similar problems it can be prevented in the future: https://github.com/galaxyproject/planemo/issues/332.

**Comment by remimarenco** [comment] 2015-10-19 13:19
Sure! Thanks for your quickness on that!

**Comment by yhoogstrate** [comment] 2015-10-19 13:41
@jmchilton brew keeps telling me there are no updates available, also after uninstalling and reinstalling planemo (0.16.0):

```
Already up-to-date.
Error: galaxyproject/tap/planemo 0.16.0 already installed
```

@remimarenco Do you succeed in updating? Thanks for the quick response guys!

**Comment by jmchilton** [comment] 2015-10-19 13:43
Opps, got distracted working on that brew update - now it is there: https://github.com/galaxyproject/homebrew-tap/commit/b8504c0698aeb886844f3ca8170a6fa93502c677

**Comment by remimarenco** [comment] 2015-10-19 13:44
@yhoogstrate Yes, used pip ;)

**Comment by remimarenco** [comment] 2015-10-19 13:49
Issue resolved from my side!

**Comment by yhoogstrate** [comment] 2015-10-19 13:49
Brew update works and the HTML output is back. I still get the warning though:
```Warning: Targetting older Galaxy which did not produce a structured test results files.```

Thanks!

**Comment by jmchilton** [comment] 2015-10-19 13:51
@yhoogstrate How old is the Galaxy you are targeting? Is it managed by planemo or by you? Do you have any local modification to Galaxy?

**Comment by yhoogstrate** [comment] 2015-10-19 13:54
I got the warning in both the version I just upgraded with brew as well as with the merge you just did on the R installation error.

**Comment by yhoogstrate** [comment] 2015-10-20 08:31
Hi @jmchilton,

I have been testing a tool and my test was failing (because the output has a few different lines). I was expecting a detailed HTML report containing the diff, stderr and stdout messages and some extra details, but I get the following output that only tells me there was a problem:

![screenshot from 2015-10-20 10 24 04](https://cloud.githubusercontent.com/assets/2264697/10601953/9e5bc266-7715-11e5-9cf3-2007f5ee218f.png)


(On the left side you see the commandline message telling that it's only a diff that causes the test to fail)

Can someone test whether failing tests work as expected and give a detailed diff output?

**Comment by remimarenco** [comment] 2015-10-20 08:53
Hi @yhoogstrate,

Maybe you should open an other issue than this one, as you seem to have it resolved.

It will be easier to track your problem, and for @jmchilton to manage it ;).

**Comment by lparsons** [comment] 2015-10-22 02:55
I'm having the same issue as @yhoogstrate (running planemo 0.18.0 on OSX 10.10). Both passing and failing tests produce the message `Warning: Targetting older Galaxy which did not produce a structured test results files.` and the resulting HTML file is devoid of any detail.

**Comment by remimarenco** [comment] 2015-10-22 14:00
In fact...I have now again the same issue too...on 0.17.0 and 0.18.0...weird as I recall 0.17.0 was working properly...:(

**Comment by jmchilton** [comment] 2015-10-22 14:02
Wonder if it depends on how you install it, maybe the new report files are missing from setuptools. Give me a second...

**Comment by jmchilton** [comment] 2015-10-22 14:14
No... something very subtle changed on the galaxy side I think - it is no longer producing details json reports of tests. Hmm...

**Comment by martenson** [comment] 2015-10-22 14:21
We were messing with Galaxy testing for quite a while. When did this issue start? 3days ago?

**Comment by jmchilton** [comment] 2015-10-22 14:24
I'm thinking it is planemo path vs galaxy path issue now.

**Closed** 2015-10-22 14:28 UTC

**Comment by jmchilton** [comment] 2015-10-22 14:35
Okay 0.18.1 is released and published to pypi and homebrew. At least release process at least is getting really smooth :(.

**Comment by yhoogstrate** [comment] 2015-10-22 15:07
![screenshot from 2015-10-22 17 05 33](https://cloud.githubusercontent.com/assets/2264697/10669040/3b57d602-78df-11e5-8998-721f52e88fb2.png)

Never been so happy to see my tools fail, Thanks @jmchilton, 0.18.1 does it for me!

**Comment by lparsons** [comment] 2015-10-22 19:51
0.18.1 fixes it for me as well, thanks for quick release @jmchilton!
